name: Manual Rundeck Trigger

on:
  workflow_dispatch:
    inputs:
      instance_ip:
        description: 'Instance IP'
        required: true
      command_to_execute:
        description: 'Command to Execute'
        required: true

jobs:
  trigger_job:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install rundeck-api library
        run: |
          pip install rundeck-api

      - name: Trigger Rundeck Job
        env:
          rundeck-url: https://rundeck-prod.entrata.io
		  rundeck-token: ${{ secrets.RUNDECK_TOKEN_PROD }}
          rundeck-job-id: 64ef7739-4eea-4cdd-b2c3-6b1c7c716d0e
		  instance_ip = '${{ github.event.inputs.instance_ip }}'
          command = '${{ github.event.inputs.command_to_execute }}'
		  
