name: Manual Rundeck Trigger

on:
  workflow_dispatch:
    inputs:
      instance_ip:
        description: 'Instance IP'
        required: true
      command_to_execute:
        description: 'Command to Execute'
        required: true

jobs:
  trigger_job:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Trigger Rundeck Job
        env:
          RUNDECK_TOKEN: ${{ secrets.RUNDECK_TOKEN_PROD }}  # Add your Rundeck API token as a secret
          RUNDECK_JOB_ID: 64ef7739-4eea-4cdd-b2c3-6b1c7c716d0e  # Replace with your Rundeck job ID
        run: |
          python -c "
          import os
          from rundeck import Rundeck

          api = Rundeck(api_token=os.environ['RUNDECK_TOKEN'], server='https://your-rundeck-instance.com')

          job_id = os.environ['RUNDECK_JOB_ID']
          instance_ip = '${{ github.event.inputs.instance_ip }}'
          command = '${{ github.event.inputs.command_to_execute }}'

          response = api.run_job(
              id=job_id,
              argString='-instance-ip {} -command-to-execute "{}"'.format(instance_ip, command)
          )

          print(response)
          "
