name: Manual Rundeck Trigger

on:
  workflow_dispatch:
    inputs:
      instance_ip:
        description: 'Instance IP'
        required: true
      command_to_execute:
        description: 'Command to Execute'
        required: true

jobs:
  trigger_job:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x 

      - name: Trigger Rundeck Job
        env:
          RUNDECK_TOKEN: ${{ secrets.RUNDECK_TOKEN_PROD }}  # Add your Rundeck API token as a secret
          RUNDECK_JOB_ID: 64ef7739-4eea-4cdd-b2c3-6b1c7c716d0e  # Replace with your Rundeck job ID
        run: |
          python - << EOF
          import os
          import requests

          api_token = os.environ['RUNDECK_TOKEN']
          job_id = os.environ['RUNDECK_JOB_ID']
          instance_ip = '${{ github.event.inputs.instance_ip }}'
          command = '${{ github.event.inputs.command_to_execute }}'

          headers = {
              'X-Rundeck-Auth-Token': api_token,
              'Content-Type': 'application/json'
          }

          payload = {
              'argString': f'-instance-ip {instance_ip} -command-to-execute "{command}"'
          }

          response = requests.post(
              f'https://rundeck-prod.entrata.io/api/32/job/{job_id}/run',
              headers=headers,
              json=payload
          )

          print(response.status_code)
          print(response.text)
          EOF
